#logging:
#  pattern:
#    console: "%d - %msg%n"  #控制台日志格式规范
##  path: D:/WechatOrder/var/log/tomcat/  #输出路径
#  file: D:/WechatOrder/var/log/tomcat/sell.log  #配置文件名
#  level:
#    com.wechat_order.sell: debug  #设置指定类的日志级别

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.220.131/Wechat_Order_sell?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null  #json全局设定非空
  redis:  #redis的配置
    host: 192.168.220.131
    port: 6379



server:
  servlet:
    #url前缀定义
    context-path: /sell


wechat:
  myAppId: wx100bce7a2d33f123
  myAppSecret: c979f4aeb76938c229038375d06f7b7f
  openAppId:
  openAppSecret:
  mchId:
  mchKey:
  keyPath:
  notifyUrl: http://cycsell.mynatapp.cc/sell/pay/notify
  templateId:
    orderStatus: "_CfGS7SqVyNPg9Op8OXzMp6aOl7X9rCkrRfiMcccms8"

projecturl:
  wechatMpAuthorize: http://cycsell.mynatapp.cc
  wechatOpenAuthorize: http://cycsell.mynatapp.cc
  sell: http://cycsell.mynatapp.cc

#设置mybatis的xml方式中xml文件所在的地方
mybatis:
  mapper-locations: classpath:mapper/*.xml
